-- [zipupPlus 포크] 이 마이그레이션은 계약서 리스크 분석 기능(contract_risk_patterns,
-- pattern_legal_provisions)용 데이터다. 이번 피벗에서 계약서 스캔 기능 자체를 제거하기로
-- 했으므로 이 테이블 데이터는 zipupPlus에서 불필요하다. 원본 production에서도 이 데이터가
-- 마이그레이션 외 경로(Studio)로 추가된 이력이 있어 완전한 재현이 불가능해 스킵한다.